### ISSUE TITLE
make errors

### ISSUE THREAD

**Issue by yg10** [cryptowatch/cw-sdk-go#16]
Out of box make command brings quite aa few of error messages like
`client/rest/rest.go:12:2: cannot find package "code.cryptowat.ch/cw-sdk-go/common"...
`...

After manually issuing 
`go get ` command for 13 packages ran make again and got the following  error message:
`client/websocket/ws_conn.go:13:2: use of internal package code.cryptowat.ch/cw-sdk-go/client/websocket/internal not allowed`
 
go version go1.11.4

**Comment by wellsjo** [comment]
this should be fixed
