### ISSUE TITLE
Reading rest api response for order book liquidity

### ISSUE THREAD

**Issue by ACFritzke** [cryptowatch/cw-sdk-go#22]
The bid and ask results are divided between the labels "base" and "quote". What do they mean?

**Comment by ddaws** [comment]
@ACFritzke can you link the API endpoint you are hitting, or the code you are referring to? 

Base and quote generally refer to the base and quote of a market, where the base is the asset being transacted and the quote is the asset the price is being quoted in. For example, for the market BTC/USD the base is BTC and the quote is USD. This means that BTC is being bought and sold and the price is quote in USD dollar. You can make a statement about the base and quote like 

> I will buy 1.5 BTC at a price of $10k USD per BTC
